### ISSUE TITLE
Times not working in calendar

### ISSUE THREAD

**Issue by maxipom** [uvsy-flutter-mobile/universy#10]
When creating a new event, the times setted are not correct

**Comment by loledesma** [comment]
@maxipom  que seria esto? algun ejemplo?

**Comment by CamiCorrales** [comment]
1) nuevo evento
2) seleccionar hora desde 12:00
3) guardar 

> El sistema cambia el orden de las horas. Quedando hora desde (la actual) y hora hasta 12:00.

![imagen](https://user-images.githubusercontent.com/38230659/98996244-4b201e80-2511-11eb-8010-b51eeb469a47.png)
![imagen](https://user-images.githubusercontent.com/38230659/98996260-52472c80-2511-11eb-9077-e0c85ca34e68.png)
![imagen](https://user-images.githubusercontent.com/38230659/98996280-583d0d80-2511-11eb-8f41-8362a6898c4a.png)

**Comment by loledesma** [comment]
Solucionado
