### ISSUE TITLE
Milestone dificil de entender para usuarios iniciales

### ISSUE THREAD

**Issue by maxipom** [uvsy-flutter-mobile/universy#14]
Al ingresar por primera vez 
se le dio la tarea al usuario de pasar a "Aprobada" una materia
la persona presiono muchas veces sobre el boton desabilitado de "Aprobar"
y salio reiteradamentes de la seccion de milestone frustandose al no saber como hacerlo
hasta que finalmente entendio que debia pasar por todos los estados

Posible solución:
Ocultar los estados que estan deshabilitados para que la persona se vea obligado a presionar el cortar
o cambiar el estilo a borde de lineas punteados
tambien se podria reveer el orden de los milestone
El orden cronologico por defecto es de arriba a abajo,
Se deberia cambiar la vista a
  Cursar
  Regularizar
  Aprobar

**Comment by loledesma** [comment]
Solucionado
