### ISSUE TITLE
No hay Volver atrás en verificá tu email

### ISSUE THREAD

**Issue by CamiCorrales** [uvsy-flutter-mobile/universy#24]
[branch: change-password]
Desde la pantalla principal:

    Recupero de contraseña
    Ingresar usuario (email)
    Siguiente

*En caso de haber ingresado mal el email, no me da la posibilidad de cambiarlo, al apretar volver, solo me deja salir de la app .

![imagen](https://user-images.githubusercontent.com/38230659/94994254-df8b7e80-056c-11eb-863d-4b53b757410d.png)

**Comment by loledesma** [comment]
Solucionado
