### ISSUE TITLE
No hay mensaje de confirmación de cambio de contraseña

### ISSUE THREAD

**Issue by CamiCorrales** [uvsy-flutter-mobile/universy#25]
[branch: change-password]
Desde la pantalla principal:

-     Recupero de contraseña
-     Ingresar usuario (email)
-     Continuar
-     Ingresar codigo
-     Ingresar las contraseñas nuevas
-     Confirmar

El sistema redirige directamente a la pagina principal de mis materias y no informa si la contraseña se cambió correctamente o no

**Comment by loledesma** [comment]
Solucionado

**Comment by loledesma** [comment]
Solucionado
