### ISSUE TITLE
Forma de actualizar estados no intuitiva

### ISSUE THREAD

**Issue by CamiCorrales** [uvsy-flutter-mobile/universy#26]
Se le brindo la app a un usuario para que pueda cambiar de estado sus materias desde "Mis Materias" y apretaba directamente en aprobada , no en cursando .

Probablemente, si cambiamos el orden de los estados de arriba hacia abajo y no de abajo hacia arriba, resulte más  entendible al usuario.

**Comment by loledesma** [comment]
Solucionado
