### ISSUE TITLE
No podes cerrar sesion si no te creas un perfil

### ISSUE THREAD

**Issue by maxipom** [uvsy-flutter-mobile/universy#27]
**Descricíón**
    Como usuario recien creado, no se encuerntra disponible la opción para cerrar sesión
ya que la misma se habilita luego de completar los datos del perfil.
Deberia incluirse la opción por mas que el perfil no este creado

Pasos de reproducción
1. Crear una cuenta nueva
2. Ingresar a la seccion perfil

**Resultado esperado**
> Se visualiza un floating action button que permita cerrar sesion

**Resultado obtenido**
> Aparece unicamente el boton "Crear Perfil"

**Comment by loledesma** [comment]
Solucionado

**Comment by loledesma** [comment]
Solucionado
