### ISSUE TITLE
Registrar y Editar Evento en calendario: no tiene lìmite de caracteres

### ISSUE THREAD

**Issue by CamiCorrales** [uvsy-flutter-mobile/universy#35]
Un largo de 100 caracteres corresponderia a un titulo de aproximadamente 3 renglones y me parece razonable,para más información está la descripción(?

![imagen](https://user-images.githubusercontent.com/38230659/99000605-4f036f00-2518-11eb-83c9-6bd7d2c371ec.png)

**Comment by loledesma** [comment]
Solucionado
