### ISSUE TITLE
Double background in notes

### ISSUE THREAD

**Issue by maxipom** [uvsy-flutter-mobile/universy#7]
**Preconditions:**
Dont have notes created.

**Steps**
1. Enter to "Mis anotaciones"
2. Press the create button (floating action button)
3. Press the cancel button (cross icon)

**Expected results**
Shows the no-message-text 

**Current results**
Shows the expected text but the background is repeated (See image)

**Evidence**
![image](https://user-images.githubusercontent.com/7583249/92337024-efeb2f00-f07c-11ea-8055-237e417d7e91.png)

**Comment by loledesma** [comment]
Lo solucione en el branch notes-bugs :)

**Comment by loledesma** [comment]
Solucionado
